### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by lauravana** [quarto-journals/jss#11]
The READNE contains a typo in the last code chunk. It wrongly states the argument include-jss-default which should be include-jss-layout.

```
format:
  jss-pdf:
    keep-tex: true
    journal:
      type: bookreview
      cite-shortnames: true
      suppress: [title]
      include-jss-layout: false
```
